apiVersion: v1
kind: Service
metadata:
  labels:
    service: cerebro
  name: cerebro
spec:
  type: NodePort
  ports:
  - name: "9009"
    port: 9009
    targetPort: 9000
    nodePort: 30000
  selector:
    service: cerebro
