apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: deploment-es7data3
  name: deploment-es7data3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
