apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    service: deploment-es7data2
  name: deploment-es7data2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
