version: '2'
services:
    cerebro:
        image: lmenezes/cerebro:0.8.3
        container_name: cerebro
        ports:
            - "9009:9000"
        command:
            - -Dhosts.0.host=http://elasticsearch:9200
    kibana:
        image: kibana:7.2.0
        container_name: kibana7
        environment:
            - I18N_LOCALE=zh-CN
            - XPACK_GRAPH_ENABLED=true
            - TIMELION_ENABLED=true
            - XPACK_MONITORING_COLLECTION_ENABLED="true"
        ports:
            - "5601:5601"
    elasticsearch:
        image: elasticsearch:7.2.0
        container_name: es7_01
        environment:
            - cluster.name=zjc-es-cluster
            - node.name=es7_01
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.seed_hosts=es7_01
            - cluster.initial_master_nodes=es7_01,es7_02
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es7data1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
    elasticsearch2:
        image: elasticsearch:7.2.0
        container_name: es7_02
        environment:
            - cluster.name=zjc-es-cluster
            - node.name=es7_02
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.seed_hosts=es7_01
            - cluster.initial_master_nodes=es7_01,es7_02
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - es7data2:/usr/share/elasticsearch/data
volumes:
    es7data1:
        driver: local
    es7data2:
        driver: local
